Traceback (most recent call last):
  File "eval.py", line 111, in <module>
    segnet.load_state_dict(torch.load(model_dir+'model_seg_'+data_name+'_'+tag+'.pt'))
  File "/opt/miniconda3/envs/cortexode/lib/python3.7/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/miniconda3/envs/cortexode/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/miniconda3/envs/cortexode/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/data/users2/washbee/speedrun/CortexODE_fork/ckpts/experiment_3_mod/model/best/model_seg_hcp_hcp_trained.pt'
